wisport/config/routes.rb
Wisport::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :events do
		get :nearby, :on => :collection
	end

  resources :do_exercises

  resources :do_sessions

  resources :images

  resources :user_login_services

	resources :my_exercises, :only => [:index]
	
	resources :my_sessions, :only => [:index]
	
	resources :likes, :only => [:create, :destroy]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/failure', to: redirect('/')

  resources :sessions

  resources :users do
		put :toggle_follow, :on => :member
	end

  resources :trainings_sessions do
		put :publish, :on => :member
	end

  resources :information

  resources :exercises do
		put :publish, :on => :member
	end

  root :to => 'pages#home'

end

wisport/app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :trainings_session_id, :visibility, :start_at, :end_at, :color, :trainings_session, :description, :address, :latitude, :longitude
  has_event_calendar
	belongs_to :trainings_session
	belongs_to :user

	validates_presence_of :trainings_session, :visibility, :start_at, :end_at, :color
	scope :published, where("visibility is 'Published'")
	
	geocoded_by :address   # can also be an IP address
	after_validation :geocode

	acts_as_gmappable :lat => 'latitude', :lng => 'longitude', :process_geocoding => :geocode?,
	                  :address => "address", :normalized_address => "address",
	                  :msg => "Sorry, not even Google could figure out where that is"
	
	def geocode?
	  (!address.blank? && (latitude.blank? || longitude.blank?)) || address_changed?
	end

	def name
		return trainings_session.title
	end

	def self.visibility_options
		["Published","Private"]
	end
	def self.color_options
		["Maroon","Orange","Gold","Olive","Pink","LightSteelBlue"]
	end
	validates_inclusion_of :visibility, :in => visibility_options, :allow_nil => false
end

wisport/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :login_required, :except => [:show ]
  # GET /events
  # GET /events.json
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @first_day_of_week = 1
    @event_strips = current_user.events.event_strips_for_month(@shown_month, @first_day_of_week)
		@forecast = HTTParty.get("http://api.wunderground.com/api/7aeb11b8b6f1a700/forecast10day/geolookup/q/autoip.json")
		unless @forecast && @forecast['forecast'] && @forecast['forecast']['simpleforecast'] && @forecast['forecast']['simpleforecast']['forecastday']
			ip = HTTParty.get("http://api.ipinfodb.com/v3/ip-city/?key=419418c11c5a24c908bd6c5f2acfe4886e7b0e26762bcf1386fdf0f0bcec39b1&ip=#{request.remote_ip}0&format=json")
			@forecast = HTTParty.get("http://api.wunderground.com/api/7aeb11b8b6f1a700/forecast10day/geolookup/q/#{ip["latitude"]},#{ip["longitude"]}.json")
			unless @forecast && @forecast['forecast'] && @forecast['forecast']['simpleforecast'] && @forecast['forecast']['simpleforecast']['forecastday']
				@forecast = HTTParty.get("http://api.wunderground.com/api/7aeb11b8b6f1a700/forecast10day/geolookup/q/Belgium/Brussels.json")
			end
		end 
		respond_to do |format|
      format.html # show.html.erb
      format.json { render json: Event.all }
    end
  end

	def nearby
		
		if params["latitude"] && params["longitude"] 
			define_map_markers [params["latitude"], params["longitude"]]
		elsif params["search_name"]
			define_map_markers params["search_name"]
		elsif request.location.latitude == 0 && request.location.longitude == 0
			define_map_markers "brussels, belgium"
		else
			my_loc = request.location
			define_map_markers
			logger.debug "AAAAAAAA #{my_loc.inspect}"
			define_map_markers [my_loc.latitude, my_loc.longitude]
		end
		@forecast = HTTParty.get("http://api.wunderground.com/api/7aeb11b8b6f1a700/forecast10day/geolookup/q/autoip.json")
		unless @forecast && @forecast['forecast'] && @forecast['forecast']['simpleforecast'] && @forecast['forecast']['simpleforecast']['forecastday']
			ip = HTTParty.get("http://api.ipinfodb.com/v3/ip-city/?key=419418c11c5a24c908bd6c5f2acfe4886e7b0e26762bcf1386fdf0f0bcec39b1&ip=#{request.remote_ip}0&format=json")
			@forecast = HTTParty.get("http://api.wunderground.com/api/7aeb11b8b6f1a700/forecast10day/geolookup/q/#{ip["latitude"]},#{ip["longitude"]}.json")
			unless @forecast && @forecast['forecast'] && @forecast['forecast']['simpleforecast'] && @forecast['forecast']['simpleforecast']['forecastday']
				@forecast = HTTParty.get("http://api.wunderground.com/api/7aeb11b8b6f1a700/forecast10day/geolookup/q/Belgium/Brussels.json")
			end
		end 
		respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @markers }
			format.js
    end
  end

	def define_map_markers qry
		if qry.class == Array
			@lat = qry[0]
			@long = qry[1]
		else
			r = Geocoder.search("Brussels, belgium")[0]
			@lat = r.latitude
			@long = r.longitude
		end
		@markers = Event.where("start_at > ?", Time.now).near(qry, 15).to_gmaps4rails do |event, marker|
			marker.infowindow render_to_string(:partial => "/events/maps_marker", :locals => { :event => event})
		end
	end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
		@json = @event.to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
		@event.start_at = Time.now
		@event.end_at = Time.now
		@my_sessions = TrainingsSession.liked_by(current_user.id).published
			.concat(TrainingsSession.owned_by(current_user.id).published)
			.concat(TrainingsSession.owned_by(current_user.id).unpublished)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
      format.js
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
		@my_sessions = TrainingsSession.liked_by(current_user.id).published
			.concat(TrainingsSession.owned_by(current_user.id).published)
			.concat(TrainingsSession.owned_by(current_user.id).unpublished)
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
		@event.user = current_user
		@event.visibility = "Published"
		@event.end_at = @event.start_at
		@my_sessions = TrainingsSession.liked_by(current_user.id).published
			.concat(TrainingsSession.owned_by(current_user.id).published)
			.concat(TrainingsSession.owned_by(current_user.id).unpublished)
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
        format.js { render js: %(window.location='#{events_path}') }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js { render action: "new"}
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event= Event.find(params[:id])
		@my_sessions = TrainingsSession.liked_by(current_user.id).published
			.concat(TrainingsSession.owned_by(current_user.id).published)
			.concat(TrainingsSession.owned_by(current_user.id).unpublished)
    respond_to do |format|
      if @event.update_attributes(params[:event])
				@event.end_at = @event.start_at
				@event.save!
        format.html { redirect_to events_path, notice: 'event was successfully updated.' }
        format.json { head :no_content }
        format.js { render js: %(window.location='#{events_path}') }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js { render action: "edit"}
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to event_url }
      format.json { head :no_content }
			format.js
    end
  end

	def publish
		@event = Exercise.find_by_id(params[:id])
		logger.debug(@event.visibility)
		if @event.visibility=="Private"
			@event.visibility = "Published"
		else
			@event.visibility = "Private"
		end
		@event.save
		respond_to do |format|
			format.html
			format.js
		end
	end
end

wisport/app/helpers/event_helper.rb
module EventHelper
end

wisport/app/views/events/_form.html.erb
<h1>New event</h1>
<%= simple_form_for(@event, remote: true, html: {class: 'form-horizontal' }) do |f| %>
	<%= f.error_notification %>

	<%= f.input :start_at, :as => :date_picker, :input_html => { :value => @event.start_at.to_date} %>

	<%= f.association :trainings_session, :collection => @my_sessions, :input_html => { "data-placeholder" => 'Choose a Session' } %>

	<%= f.input :color, :collection => Event.color_options %>
	<%= f.input :address %>

	<%= f.error :base %>
  <div class="form_buttons">
    <%= f.button :submit, class: 'btn btn-primary' %>
		<%= link_to 'Cancel', events_path, class: 'btn btn-danger' %>
  </div>
<% end %>
<script type = "text/javascript">
	$(function(){
		$('#event_trainings_session_id').chosen();
		$("#event_start_at").datepicker();
		$("#event_start_at").datepicker("option", "dateFormat", "dd-mm-yy" );
	});
</script>

wisport/app/views/events/_google_maps.html.erb
<%= gmaps(:markers => {:data => markers, :options => { :raw => '{ optimized: false }',"custom_infowindow_class" => "maps_popup" } } ) %> 
<script type = "text/javascript">
$(function() {
	Gmaps.map.infobox = function(boxText) {
		return {
			content: boxText
			,disableAutoPan: false
			,maxWidth: 0
			,pixelOffset: new google.maps.Size(-140, 0)
			,zIndex: null
			,boxStyle: { 
				background: "url('http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.5/examples/tipbox.gif') no-repeat"
				,opacity: 0.85
				,width: "280px"
			}
			,closeBoxMargin: "10px 2px 2px 2px"
			,closeBoxURL: "http://www.google.com/intl/en_us/mapfiles/close.gif"
			,infoBoxClearance: new google.maps.Size(1, 1)
			,isHidden: false
			,pane: "floatPane"
			,enableEventPropagation: false
		}
	};	
});
</script>

wisport/app/views/events/_maps_marker.html.erb
<h4><%= event.trainings_session.title %></h4>
<p><%= event.description %></p>
Go to the <%= link_to "event", event %>

wisport/app/views/events/destroy.js.erb
var event = $(".ec-event-<%= @event.id %>");
var cell = event.parent();
event.remove();
cell.addClass("ec-no-event-cell");

wisport/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

wisport/app/views/events/index.html.erb
<div class="row-fluid">
	<div class="span5">

		<h1>Calendar
		</h1>
	</div>
	<div class="span7">
		<p align="right">	
			<p align="right">
				<% if @forecast && @forecast['forecast'] %>
					<a href="#" onclick="expand_weather()" class="btn btn-info">Show Weather Forecast</a>
				<% end %>
				<%= link_to 'Map', nearby_events_path, class: "btn btn-success" %>
				<%= link_to "New Event", new_event_path, remote: true, class: "btn btn-primary" %>
			</p>
		</p>
	</div>
</div>
<% if @forecast && @forecast['forecast'] %>
	<div class="row-fluid" id="weatherMAN" style="display: none">
		<div class="span1">
			<div class="row-fluid">
			</div>
			<div class="row-fluid">
				<%= @forecast['location']['city'] %>
			</div>
			<div class="row-fluid">
			</div>
		</div>
		<% @forecast['forecast']['simpleforecast']['forecastday'].each do |b| %>
		<div class="span1 forecastday">
			<div class="row-fluid">
				<div class="span12">
					<%= image_tag b['icon_url'] %>
				</div>
			</div>
			<div class="span12">
				<div class="row-fluid">
					<div class="span12">
						<%= b["date"]["day"] %> <%= b["date"]["monthname"][0,3] %>		
					</div>	
				</div>
				<div class="row-fluid">
					<div class="span12">
						<span class="temperature_arrow"><%= image_tag "arrow_high.png" %></span>	<%= b["high"]["celsius"] %>	<span class="temperature_arrow"><%= image_tag "arrow_low.png" %></span>	<%= b["low"]["celsius"] %>
					</div>	
				</div>
			</div>
		</div>
		<% end %>
	</div>
<% end %>
<%= raw(event_calendar) %>

wisport/app/views/events/nearby.html.erb
<div class = "row-fluid">
	<div class = "span5">

		<h1>Events On a Map
		</h1>
	</div>
	<div class = "span7">
		<p align = "right">	
			<p align = "right">
				<% if @forecast && @forecast['forecast'] %>
				<a href = "#" onclick="expand_weather()" class="btn btn-info">Show Weather Forecast</a>
				<% end %>
				<%= link_to 'Calendar', events_path, class: "btn btn-success" %>
				<%= link_to "New Event", new_event_path, remote: true, class: "btn btn-primary" %>
			</p>
		</p>
	</div>
</div>
<% if @forecast && @forecast['forecast'] %>
<div class = "row-fluid" id="weatherMAN" style="display: none">
	<div class = "span1">
		<div class = "row-fluid">
		</div>
		<div class = "row-fluid">
			<%= @forecast['location']['city'] %>
		</div>
		<div class = "row-fluid">
		</div>
	</div>
	<% @forecast['forecast']['simpleforecast']['forecastday'].each do |b| %>
	<div class = "span1 forecastday">
		<div class = "row-fluid">
			<div class = "span12">
				<%= image_tag b['icon_url'] %>
			</div>
		</div>
		<div class = "span12">
			<div class = "row-fluid">
				<div class = "span12">
					<%= b["date"]["day"] %> <%= b["date"]["monthname"][0,3] %>		
				</div>	
			</div>
			<div class = "row-fluid">
				<div class = "span12">
					<span class = "temperature_arrow"><%= image_tag "arrow_high.png" %></span>	<%= b["high"]["celsius"] %>	<span class="temperature_arrow"><%= image_tag "arrow_low.png" %></span>	<%= b["low"]["celsius"] %>
				</div>	
			</div>
		</div>
	</div>
	<% end %>
</div>
<% end %>
<%= form_tag nearby_events_path, :method => 'get', :id => "exercises_search" do %>
	<%= text_field_tag :search_name, params[:search_name], id: "name_search" %>
	<%= submit_tag "Set Location", class: "btn maps_search_button" %> OR 
	<%= link_to 'Use my current location','#', class: "btn maps_search_button", id: "getLocation" %>
<% end %>
<div id="google_map"> 
<%= render :partial => 'google_maps', locals: {markers: @markers} %>
</div>
<script type = "text/javascript">
$(function() {
	$("#getLocation").click(function() {
		navigator.geolocation.getCurrentPosition(
			onSuccess,
			onError, {
				enableHighAccuracy: true,
				timeout: 20000,
				maximumAge: 120000
			}
		);
		function onSuccess(position) {
			//alert('latitude=' + position.coords.latitude +'&longitude=' + position.coords.longitude);
			$.ajax({
				url: "/events/nearby",
				dataType: "script",
				data: 'latitude=' + position.coords.latitude +'&longitude=' + position.coords.longitude
			 })
		}
		function onError(err) {
			var message;
			switch (err.code) {
				case 0:
				alert('Unknown error: ' + err.message);
				break;
				case 1:
				alert('You denied permission to retrieve a position.');
				break;
				case 2:
				alert('The browser was unable to determine a position: ' + error.message);
				break;
				case 3:
				alert('The browser timed out before retrieving the position.');
				break;
			}
		}
	});	
});
</script>

wisport/app/views/events/nearby.js.erb
markers = <%=raw(@markers)%>
console.log(markers[0]);
Gmaps.map.replaceMarkers(markers);
var user_image = "/assets/50px-Wikimap-blue-dot.png";
<% if params["latitude"] && params["longitude"] %>
var lat = <%= params["latitude"] %>;
var long = <%= params["longitude"] %>;


//add current location marker
Gmaps.map.addMarkers([{
  "lng": long,
  "lat": lat,
  "width":"40",
  "height":"48",
  "picture": user_image
}]);

//center the screen on your current location
Gmaps.map.serviceObject.setCenter(new google.maps.LatLng(lat, long));
<% end %>
Gmaps.map.serviceObject.setZoom(10);

wisport/app/views/events/new.html.erb
<%= render "form" %>

wisport/app/views/events/new.js.erb
$('#event_form').remove();
$('#container').prepend(' <%=j floating_form "form", id: "event_form" %>');
$(".floating_form_close").click(function() {hide_popups();});
$("a:contains('Cancel')").attr("href", "#").click(function() {hide_popups();});
open_floating_form('event_form');

wisport/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row-fluid">
	<div class="span7">
		<h1> <%= @event.name %> </h1>
	</div>
	<div class="span5">
		<p align="right">
			<% trainings_session = @event.trainings_session  %>
			<%= link_to 'Do!', {controller: "do_sessions", action: "new", do_session: {trainings_session_id: trainings_session.id, user_id: current_user.id}}, remote: true, class: "btn btn btn-success" %>
			<%= link_to 'show Sessions', trainings_session, class: "btn btn btn-success" %>
			<% if @event.user == current_user %>     
				<%= link_to 'Edit', edit_event_path(@event), class:"btn", remote: true %>
				<%= link_to 'Destroy', @event, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
			<% else %>
				Owner:
				<%= link_to @event.user.username, @event.user %>
			<% end %>
		</p>
		</br>
		</br>
	</div>
</div>
<div class="row-fluid">
	<div class="span9">
		<%= gmaps4rails(@json) %>
	</div>
	<div class="span3">
		<b>Start:</b>
		<%= @event.start_at %>
		</br>
		<b>End:</b>
		<%= @event.end_at %>
		</br>
		<b>Longitude:</b>
		<%= @event.longitude %>
		</br>
		<b>Latitude:</b>
		<%= @event.latitude %>
		</br>
		<b>Address:</b>
		<%= @event.address %>
	</div>
	<div class="span6"%>
		<b>Exercises:</b> 
		</br>
		<table class="table table-striped">
			<tr>
				<th>Name</th>
				<th>Type</th>
				<th>Owner</th>
			</tr>
			<% @event.trainings_session.exercises.each do |exercise| %>
				<tr>
					<td><%= link_to exercise.name, exercise %></td>
					<td><%= exercise.type %></td>
					<td><%= link_to exercise.owner.username, exercise.owner %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>
<%= link_to 'Back', events_path %>