wisport/config/routes.rb
Wisport::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :events do
		get :nearby, :on => :collection
	end

  resources :do_exercises

  resources :do_sessions

  resources :images

  resources :user_login_services

	resources :my_exercises, :only => [:index]
	
	resources :my_sessions, :only => [:index]
	
	resources :likes, :only => [:create, :destroy]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/failure', to: redirect('/')

  resources :sessions

  resources :users do
		put :toggle_follow, :on => :member
	end

  resources :trainings_sessions do
		put :publish, :on => :member
	end

  resources :information

  resources :exercises do
		put :publish, :on => :member
	end

  root :to => 'pages#home'

end

wisport/app/models/information.rb
class Information < ActiveRecord::Base
  attr_accessible :description, :images_attributes, :image_ids, :videos_attributes

  belongs_to :exercise
  has_many :images
	has_many :videos
  
  accepts_nested_attributes_for :images, allow_destroy: true
	accepts_nested_attributes_for :videos, allow_destroy: true
end

wisport/app/controllers/information_controller.rb
class InformationController < ApplicationController
	before_filter :login_required
  # GET /information
  # GET /information.json
  def index
    @information = Information.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @information }
    end
  end

  # GET /information/1
  # GET /information/1.json
  def show
    @information = Information.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @information }
    end
  end

  # GET /information/new
  # GET /information/new.json
  def new
    @information = Information.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @information }
    end
  end

  # GET /information/1/edit
  def edit
    @information = Information.find(params[:id])
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(params[:information])

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render json: @information, status: :created, location: @information }
      else
        format.html { render action: "new" }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /information/1
  # PUT /information/1.json
  def update
    @information = Information.find(params[:id])

    respond_to do |format|
      if @information.update_attributes(params[:information])
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information = Information.find(params[:id])
    @information.destroy

    respond_to do |format|
      format.html { redirect_to information_index_url }
      format.json { head :no_content }
    end
  end
end

wisport/app/helpers/information_helper.rb
module InformationHelper
end

wisport/app/views/information/_form.html.erb
<%= simple_form_for(@information, html: {class: 'form-horizontal' }) do |f| %>
	<%= f.error_notification %>
	
	<%= f.input :media %>
	<%= f.input :description, input_html: {:rows => 5} %>
	
	<%= f.error :base %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
		<%= link_to 'Cancel', information_index_path, class: 'btn btn-danger' %>
  </div>
<% end %>

wisport/app/views/information/edit.html.erb
<h1>Editing information</h1>

<%= render 'form' %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

wisport/app/views/information/index.html.erb
<h1>Listing information</h1>

<table>
  <tr>
    <th>Media</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @information.each do |information| %>
  <tr>
    <td><%= information.media %></td>
    <td><%= information.description %></td>
    <td><%= link_to 'Show', information %></td>
    <td><%= link_to 'Edit', edit_information_path(information) %></td>
    <td><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Information', new_information_path %>

wisport/app/views/information/new.html.erb
<h1>New information</h1>

<%= render 'form' %>

<%= link_to 'Back', information_index_path %>

wisport/app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Media:</b>
  <%= @information.media %>
</p>

<p>
  <b>Description:</b>
  <%= @information.description %>
</p>


<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>