wisport/config/routes.rb
Wisport::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :events do
		get :nearby, :on => :collection
	end

  resources :do_exercises

  resources :do_sessions

  resources :images

  resources :user_login_services

	resources :my_exercises, :only => [:index]
	
	resources :my_sessions, :only => [:index]
	
	resources :likes, :only => [:create, :destroy]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/failure', to: redirect('/')

  resources :sessions

  resources :users do
		put :toggle_follow, :on => :member
	end

  resources :trainings_sessions do
		put :publish, :on => :member
	end

  resources :information

  resources :exercises do
		put :publish, :on => :member
	end

  root :to => 'pages#home'

end

wisport/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

wisport/app/views/layouts/_nav.html.erb
.dczjzev zevhihihi
<a href="#"> lalalalal</a>

wisport/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
	<![endif]-->
	<%= stylesheet_link_tag "application", :media => "all"  %>
	<%= javascript_include_tag :application %>
	<%= csrf_meta_tag %>
	<%= yield(:head) %>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body <%= yield :body_tag %> >
	<div id="overlay" class="popup hidden" style="display: block; "></div>
	<div id="container" class="container">
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					
					<%= link_to content_tag(:span, "Wi", class: "logo_wi")+content_tag(:span, "Sport", class: "logo_sport"), root_path, class: "brand" %>
					<div class="nav-collapse">
						<ul class="nav pull-left">
							<% if current_user %>
								<li class="dropdown">
								  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
								    Exercices
								    <b class="caret"></b>
								  </a>
								  <ul class="dropdown-menu">
								    <li><%= link_to "My Exercices", my_exercises_path %></li>
										<li><%= link_to "All Exercices", exercises_path %></li>
								  </ul>
								</li>
								<li class="dropdown">
								  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
								    Training Sessions
								    <b class="caret"></b>
								  </a>
								  <ul class="dropdown-menu">
								    <li><%= link_to "My Training Sessions", my_sessions_path %></li>
										<li><%= link_to "All Training Sessions", trainings_sessions_path %></li>
								  </ul>
								</li>
								<li><%= link_to "Schedule", events_path %></li>
							<% end %>
						</ul>
						<ul class="nav pull-right">
							<% if current_user %>
								<li> <%= link_to "Welcome #{current_user.username}", current_user %>  </li>
								<li class="divider-vertical"></li>
								<li class="hilight"> <%= link_to "Log Out", logout_path %>  </li>
							<% else %>
								<li> <%= link_to "Log In", login_url, :remote => true %> </li>
								<li class="divider-vertical"></li>
								<li class="hilight"> <%= link_to "Sign Up", signup_path %>  </li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="row-fluid"> 
			<div class="span12">
				<% flash.each do |name, msg| %>
				<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
					<a class="close" data-dismiss="alert">×</a>
					<%= msg %>
				</div>
				<% end %>

				<%= content_tag :h1, yield(:title) if show_title? %>
				<%= yield %>
			</div>
		</div class="row-fluid">
	</div>
	<%= yield :scripts %>
		<% if false#Rails.env.development? %>
		<br/>
		<div id="debug">
			<pre>
			DEBUG
			<%= debug(params) if Rails.env.development? %><br/>
			<br/>
			<table>
				<thead>
					<tr>
						<th>SESSION</th>
					</tr>
				</thead>
				<tbody>
					<% session.keys.each do |key| %>
					<tr>
						<td><%= key %></td>
						<td><%= session[key] %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		</pre>
		<% end %>
</body>
</html>