wisport/config/routes.rb
Wisport::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :events do
		get :nearby, :on => :collection
	end

  resources :do_exercises

  resources :do_sessions

  resources :images

  resources :user_login_services

	resources :my_exercises, :only => [:index]
	
	resources :my_sessions, :only => [:index]
	
	resources :likes, :only => [:create, :destroy]

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/failure', to: redirect('/')

  resources :sessions

  resources :users do
		put :toggle_follow, :on => :member
	end

  resources :trainings_sessions do
		put :publish, :on => :member
	end

  resources :information

  resources :exercises do
		put :publish, :on => :member
	end

  root :to => 'pages#home'

end

wisport/app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation, :exercises, :trainings_sessions

	has_many :exercises, :foreign_key => "owner_id"
	has_many :trainings_sessions
  has_many :user_login_services
	has_many :events
	has_many :do_sessions
  has_and_belongs_to_many :friends,
		:class_name => "User",
		:association_foreign_key => "friend_id",
		:join_table => "friends"
attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

	def self.search_by_name(name)
		if name && ! name.empty?
			where('username LIKE ?', "%#{name}%")
		else
			scoped
		end
	end

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
  
  def self.from_omniauth(auth)
    user = joins(:user_login_services).where("user_login_services.provider = ? AND user_login_services.uid = ?", auth["provider"], auth["uid"]).first
    if user
      user.set_service(auth)
      user
    else
      create_from_omniauth(auth)
    end
  end
  
  def set_service(auth)
    s = user_login_services.where("provider = ?", auth["provider"])
    if s.empty?
      user_login_services.new( provider: auth["provider"], uid: auth["uid"], 
      login: auth["info"]["email"], acces_token: auth["credentials"]["token"],
      refresh_token: auth["credentials"]["refresh_token"],
      token_expiration: Time.at(auth["credentials"]["expires_at"].to_i),
      image: auth["info"]["image"],
      profile_link: auth["extra"]["raw_info"]["link"]
      )
    else
      s.first.update_attributes!( acces_token: auth["credentials"]["token"],
      refresh_token: auth["credentials"]["refresh_token"],
      token_expiration: Time.at(auth["credentials"]["expires_at"].to_i),
      image: auth["info"]["image"],
      profile_link: auth["extra"]["raw_info"]["link"]
      )
    end
  end  

  def self.create_from_omniauth(auth)
    new_user = new do |user|
      user.username = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.user_login_services.new( provider: auth["provider"], uid: auth["uid"], 
      login: auth["info"]["email"], acces_token: auth["credentials"]["token"],
      refresh_token: auth["credentials"]["refresh_token"],
      token_expiration: Time.at(auth["credentials"]["expires_at"].to_i),
      image: auth["info"]["image"],
      profile_link: auth["extra"]["raw_info"]["link"]
      )
    end
    new_user.save(:validate => false)
    new_user
  end

	def followers
		User.joins(:friends).find(:all, :conditions => ["friend_id=?", self])
	end

	def followers_exercises
		@exercises = []
		friends.each do |friend|
			@exercises += friend.exercises.published
		end
		return @exercises
	end
	def followers_sessions
		@trainings_sessions = []
		friends.each do |friend|
			@trainings_sessions += friend.trainings_sessions.published
		end
		return @trainings_sessions
	end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

wisport/app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'will_paginate/array'
  before_filter :login_required, :except => [:new, :create]

	def index
		@users = User.search_by_name(params[:q])
		respond_to do |format|
			format.html
			format.js
			format.json { render json: @users.map { |u| {:id => u.id, :name => u.username} } }
		end
	end
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
		@exercises = @user.exercises.paginate(:page => params[:my_exercises_page])
		@trainings_sessions = @user.trainings_sessions.paginate(:page => params[:my_sessions_page])
		@followers_exercises = @user.followers_exercises.paginate(:page => params[:followers_page])
		@followers_sessions = @user.followers_sessions.paginate(:page => params[:followers_page])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end

	def toggle_follow
		@user = User.find_by_id(params[:id])
		if @current_user.friends.include? @user
			@current_user.friends.delete(@user)
		else
			@current_user.friends << @user
		end
		respond_to do |format|
			format.html
			format.js
		end
	end
end

wisport/app/helpers/users_helper.rb
module UsersHelper
	def profile_picture user
		if (not user.user_login_services.empty?) && user.user_login_services.first.image
			user.user_login_services.first.image
		else
			avatar_url(user)
		end 
	end
	def avatar_url user
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}.png?s=48&"
	end
end

wisport/app/views/users/_follow.html.erb
<div class="follow" id='follow'>
	<%= "#{@user.followers.size} #{"follower".pluralize(@user.followers.size)}" %>
	<br/>
<% if @user != @current_user  %>
	<% if @current_user.friends.include?(@user) %>
		<%= button_to "Unfollow", toggle_follow_user_path(@user), class: "btn btn-danger", :method => :put, :remote => true %>
	<% else %>
		<%= button_to "Follow", toggle_follow_user_path(@user), class: "btn btn-primary", :method => :put, :remote => true %>
	<% end %>
<% end %>
</div>

wisport/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

wisport/app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

wisport/app/views/users/follow.js.erb
var x = $('div#follow.follow');
x.parent().append(' <%= j render :partial => "follow" %> ');
x.remove();

wisport/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>username</th>
    <th>email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trainings session', new_user_path %>

wisport/app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

wisport/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row-fluid" >
<div class="row">
	<div class="profile_image offset1 span2" >
		<%= image_tag profile_picture(@user) %>
		<br/>
		<%= render :partial => 'follow' %>
	</div>
	<div class="span9">
		<div class="user_info">
			<h1> <%= @user.username %> </h1>
			<p>
				<b>Name:</b>
				<%= @user.username %>

			</p>
			<p>
				<b>email:</b>
				<%= @user.email %>
			</p>
			<% @user.user_login_services.each do |user_service| %>
					<p>
						<b>Link to Google+ profile:</b>
						<%=link_to  "#{user_service.provider} profile", user_service.profile_link %>
					</p>
			<% end %>
			<% if @user == @current_user %>
				<%= link_to 'Edit', edit_user_path(@user) %> |
			<% end %>
			<%= link_to 'Back', users_path %>
		</div>
	</div>
</div>

<div class="span6">
<h5> Upcomming Events </h5>
		<%= render ('pages/upcomming_events') %>
</div>

<div class="span5">
<h5> Recently passes events </h5>
	<%= render ('pages/past_events') %>
</div>
<div class="span11">
<% if @exercises.empty? %>
        <p>You have not yet created an exercise. Create your own <%= link_to "exercises", new_exercise_path %> </p>
<% else %>
        <h2>My Exercises</h2>
        <%= render :partial => "exercises/exercise_list", :locals => {:exercise_list => @exercises, :publishable => true, :param_name => :my_exercises_page} %>
<% end %>
</div>
<div class="span11">
<% if @user.friends.empty? %>
	<p>You are not following anyone that published exercises. Look for more <%= link_to "friends", users_path %> to follow </p>
<% elsif @followers_exercises.empty? %>
	<p>None of you friends has published any exercises. Look for more <%= link_to "friends", users_path %> to follow </p>
<% else %>
	<h2>Followed Exercises</h2>
	<%= render :partial => "exercises/exercise_list", :locals => {:exercise_list => @followers_exercises, :param_name => :followers_page} %>
<% end %>
</div>
<br/>
<div class="span11">
<% if @trainings_sessions.empty? %>
        <p>You have not yet created an exercise. Create your own <%= link_to "training sessions", new_trainings_session_path %> </p>
<% else %>
        <h2>My Sessions </h2>
        <%= render :partial => "trainings_sessions/trainings_sessions_list", :locals => {:trainings_sessions_list => @trainings_sessions, :publishable => true, :param_name => :my_sessions_page } %>
<% end %>
</div>
<div class="span11">
<% if @user.friends.empty? %>
        <p>You are not following anyone that published trainings sessions. Look for more <%= link_to "friends", users_path %> to follow </p>
<% elsif @followers_sessions.empty? %>
        <p>None of you friends has published any trainings sessions. Look for more <%= link_to "friends", users_path %> to follow </p>
<% else %>
        <h2>Followed Sessions</h2>
        <%= render :partial => "trainings_sessions/trainings_sessions_list", :locals => {:trainings_sessions_list => @followers_sessions, :param_name => :followers_page} %>
<% end %>
</div>

</div>

wisport/app/views/users/toggle_follow.js.erb
var x = $('div#follow.follow');
x.parent().append(' <%= j render :partial => "follow" %> ');
x.remove();